server:
  #端口号
  port: 8787

spring:
  #数据库的配置
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_p?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC

  thymeleaf:
    #关闭thymeleaf的缓存
    cache: false
    mode: HTML

  redis:
    host: 192.168.199.20
    port: 6379
    database: 1
    lettuce:
      pool:
        min-idle: 0
        max-wait: -1
        max-idle: 8
        max-active: 8
    timeout: 0

#日志
logging:
  # level: debug
  #日志路径
  file:
    name: log/myLog.log


