# spring:
#   #数据库的配置
#   datasource:
#     password: root
#     username: root
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://localhost:3306/mybatis_p?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC